### GET all categories with the current products
GET http://localhost:8080/categories

### GET all products from selected category
GET http://localhost:8080/categories/0/products

### GET all products from another selected category
GET http://localhost:8080/categories/3/products

### GET all products from selected category - test invalid ID
GET http://localhost:8080/categories/999/products

### GET product details from a selected product
GET http://localhost:8080/product/1001

### GET product details from another selected product
GET http://localhost:8080/product/1020

### GET product details from another selected product
GET http://localhost:8080/product/1009

### GET product details from a selected product - test invalid ID
GET http://localhost:8080/product/999

### POST a product into basket
POST http://localhost:8080/addToBasket
Content-Type: application/json

{
  "productId": 1001,
  "amount": 1
}

### POST a product into basket
POST http://localhost:8080/addToBasket
Content-Type: application/json

{
  "productId": 1017,
  "amount": 8
}

### POST a product into basket - test not enouth amount
POST http://localhost:8080/addToBasket
Content-Type: application/json

{
  "productId": 1005,
  "amount": 9
}

### POST a product into basket - test sold out
POST http://localhost:8080/addToBasket
Content-Type: application/json

{
  "productId": 1005,
  "amount": 8
}

### POST a product into basket - test sold out
POST http://localhost:8080/addToBasket
Content-Type: application/json

{
  "productId": 1005,
  "amount": 1
}

### POST a product into basket - test invalid ID
POST http://localhost:8080/addToBasket
Content-Type: application/json

{
  "productId": 0,
  "amount": 0
}

### GET total statistic of all products
GET http://localhost:8080/statistics?method=total


### GET total statistic of all products
GET http://localhost:8080/statistics?method=avg


### GET total statistic of most clicked products
GET http://localhost:8080/statistics?method=hottest

### GET total statistic of most clicked products - test wrong request parameter
GET http://localhost:8080/statistics?method=high